### ISSUE TITLE
Setup Sentry and create logger to catch errors 

### ISSUE THREAD

**Issue by pallabez** [Real-Dev-Squad/website-goals#74]

**Comment by shmbajaj** [comment]
Hey @pallabez please assign this issue to me.

**Comment by shmbajaj** [comment]
Hey @pallabez please assign this issue to me.

**Comment by shmbajaj** [comment]
## What is Sentry 
Sentry is a tool to track errors, capture crashes and monitor performance.
Sentry doesn't impact a website's performance.

## Setup Project in Sentry


## Installation and Minimum Configuring
```js
// Install sentry in nuxt
yarn add @nuxtjs/sentry

// add to nuxt.config.js
  modules: [
    '@nuxtjs/sentry'
  ],

// config sentry object in nuxt.config.js
  sentry: {
    dsn: process.env.SENTRY_DSN || '',
  }

// create .env add sentry DSN
SENTRY_DSN = <value>
```

```sh
# create .sentryclirc file and add the following
[defaults]
org = <your_sentry_org> # real-dev-squad
project = <your_sentry_project> # website-goal
url = <your_sentry_url> # https://real-dev-squad.sentry.io/

```
<details>
<summary> More on Installation Methods (in order of preference by sentry) </summary>

- Using NPM or YARN (bundle with code)
- Lazy Loading CDN (lazy load after app js or when an error happens)
- Using CDN  (PS: not a preferred method)
- Check More From: [Here](https://docs.sentry.io/platforms/javascript/install/)

</details>

## Add More Options To Sentry Configuration
- Enabling Source Maps
   - **Source Maps:** Source maps are a way to map the code you wrote (the "source code") to the code that actually gets executed in the browser (the "compiled code"). This is useful because the compiled code is often more difficult to understand and debug than the original source code. 
   ```js
   // enable publish-releases and source-map inside nuxt.config.js
   sentry:{
            publishRelease: true,
            sourceMapStyle: 'hidden-source-map',
   }
   ```
- Using Sentry in PROD Envrionment Only
- Adding Tracing Sample Rate
    - The `tracesSampleRate` value can be between 0.0 and 1.0 (percentage of requests to capture) and Sentry documentation strongly recommends reducing the value from the default 1.0. 
   ```js
   // install tracing
   yarn add @sentry/tracing
   
   // add tracing prop to sentry objet inside nuxt.config.js
   sentry: {
    tracing: {
      tracesSampleRate: 1.0,
      browserTracing: {},
      vueOptions: {
        trackComponents: true,
        },
      }
    }
    ```


## Refferences
- [Sentry NuxtJs Module](https://sentry.nuxtjs.org/)
- [Sentry VueJs Guide](https://docs.sentry.io/platforms/javascript/guides/vue/)
- [More on Hidden Source Map | DevTool | Webpack](https://webpack.js.org/configuration/devtool)
- [blog/how-to-use-sentry-with-nuxt-js](https://lucas.love/blog/how-to-use-sentry-with-nuxt-js)

## Checklist
- [ ] Check Configuring tracing sampling rate at runtime and reducing the value from default value
- [ ] Check Sentry Usage to catch errors manually (By default, Sentry catches automatically): [Sentry NuxtJs Module Usage Guide](https://sentry.nuxtjs.org/guide/usage/)
- [ ] Lazy Loading Sentry
- [ ] Load Sentry in Production Environment Only
- [ ] Source Map Enabled
- [ ] Explore More Options for RDS Wide Configuration

**Comment by shmbajaj** [comment]
`update:` Trying to set up sentry with nuxt client-side configuration using the plugin.
